// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGsI5xL5u-RlHS6N713Yeg2RbreOCuIG0',
    appId: '1:21456792445:web:3e19a6a7d521a9b3e3fa14',
    messagingSenderId: '21456792445',
    projectId: 'smarthome-961a1',
    authDomain: 'smarthome-961a1.firebaseapp.com',
    databaseURL: 'https://smarthome-961a1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smarthome-961a1.appspot.com',
    measurementId: 'G-MK4JS8CYB0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdIPpVvVNCIFNMHNg6m_iy09VVJUY9WI0',
    appId: '1:21456792445:android:74f86569180744f7e3fa14',
    messagingSenderId: '21456792445',
    projectId: 'smarthome-961a1',
    databaseURL: 'https://smarthome-961a1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smarthome-961a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxmYwDT3Nmqt75xOitLrm_XW7eFRWVX-8',
    appId: '1:21456792445:ios:0ee22acddae0d8a7e3fa14',
    messagingSenderId: '21456792445',
    projectId: 'smarthome-961a1',
    databaseURL: 'https://smarthome-961a1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smarthome-961a1.appspot.com',
    iosClientId: '21456792445-df6jdamqd7fv4m5gm1agv15mnl0odhqr.apps.googleusercontent.com',
    iosBundleId: 'com.example.shrine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxmYwDT3Nmqt75xOitLrm_XW7eFRWVX-8',
    appId: '1:21456792445:ios:0ee22acddae0d8a7e3fa14',
    messagingSenderId: '21456792445',
    projectId: 'smarthome-961a1',
    databaseURL: 'https://smarthome-961a1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smarthome-961a1.appspot.com',
    iosClientId: '21456792445-df6jdamqd7fv4m5gm1agv15mnl0odhqr.apps.googleusercontent.com',
    iosBundleId: 'com.example.shrine',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGsI5xL5u-RlHS6N713Yeg2RbreOCuIG0',
    appId: '1:21456792445:web:ddc6429c3750d1fbe3fa14',
    messagingSenderId: '21456792445',
    projectId: 'smarthome-961a1',
    authDomain: 'smarthome-961a1.firebaseapp.com',
    databaseURL: 'https://smarthome-961a1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smarthome-961a1.appspot.com',
    measurementId: 'G-ZHPZMWF34D',
  );
}
